pipeline {
    agent any

    environment{
        CREATE_SCHEMA = "true"
        RUN_APP = "false"
        DATABASE_URI = sqlite:///data.db
    stages {
        stage('Setup') {
            steps { 
                sh "bash jenkins/setup.sh"
                //
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
                //
            }
        }
        stage('Create Schema') {
           steps {
               script{
                   if(env.CREATE_SCHEMA == "true"){
                      sh "bash jenkins/create_schema.sh"
                      
            }
        }
    }
}   

          stage('Run') {
            
            steps {
                if(env.RUN_SCHEMA == "true"){
                      sh "bash/jenkins/run_app.py"
                //
            }
        }
    }
}
