pipeline {
    agent any

    environment{
        CREATE_SCHEMA = "true"
        RUN_APP = "false"
        DATABASE_URI = "sqlite:///data.db"
            }
    stages {
        stage('Setup') {
            steps { 
                sh "bash Jenkins/setup.sh"
                //
            }
        }
        stage('Test') {
            steps {
                sh "bash Jenkins/test.sh"
                //
            }
        }
        stage('Create Schema') {
           steps {
               script{
                   if(env.CREATE_SCHEMA == "true"){
                      sh "bash Jenkins/create_schema.sh"
                      
            }
        }
    }
}   

          stage('Run') {
            
            steps {
                script{
                if(env.RUN_SCHEMA == "true"){
                      sh "bash Jenkins/run_app.py"
                //
                }
                }
            }
        }
    }
}
