#!/bin/bash
#export DATABASE_URI
export DATABASE_URI= sqlite:///data.db

# install apt packages (python3 python3-pip python3-venv)
sudo apt-get install python3 python3-pip python3-venv

# create and activate venv
python3 -m venv venv
source venv/bin/activate

# install pip requirements
pip3 install -r requirements.txt
#run pytest
python3 -m pytest \
      --cov=application \
      --cov-report term -missing
      --cov-report xml:coverage.xml \
      
#run create.py to create schema
if [$CREATE_SCHEMA == 'true']
then
    echo "creating schema"
    python3 create.py
fi

python3 app.py